controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f e e 2 2 2 2 2 2 e f f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f f . 
        . . e f e 4 d d d d 4 e f f d f 
        . . e 4 d d e 2 2 2 2 f e f b f 
        . . . e d d e 2 2 2 2 f 4 f b f 
        . . . . e e f 5 5 4 4 f . f c f 
        . . . . . f f f f f f f . f f . 
        . . . . . . . . . f f f . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d e e e e e f . . . 
        . . . f e 4 e d d 4 f . . . . . 
        . . . f 2 2 e d d e f . . . . . 
        . . f f 5 5 f e e f f f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . f f e e e e f 2 f . . . . 
        . . f f e e e e f 2 2 2 f . . . 
        . . f e e e f f e e e e f . . . 
        . . f f f f e e 2 2 2 2 e f . . 
        . . f e 2 2 2 f f f f e 2 f . . 
        . f f f f f f f e e e f f f . . 
        . f f e 4 4 e b f 4 4 e e f . . 
        . f e e 4 d 4 1 f d d e f f . . 
        . . f e e e 4 d d d d f d d f . 
        . . . . f e e 4 e e e f b b f . 
        . . . . f 2 2 2 4 d d e b b f . 
        . . . f f 4 4 4 e d d e b f . . 
        . . . f f f f f f e e f f . . . 
        . . . . f f . . . f f f . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `],
    500,
    false
    )
    mySprite.startEffect(effects.trail, 500)
    pause(1000)
    arrow = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . 4 . . . . 
        . . . 5 . . . . . . . . . . . . 
        . 2 . . 5 . . . . . 5 . 4 . . . 
        . . . 2 . 5 . . 2 . . 5 2 2 . . 
        . . . 5 2 . . 2 5 2 . 2 5 2 2 . 
        . 5 4 4 2 5 2 5 4 5 2 5 4 5 2 2 
        5 . 5 4 2 5 2 2 5 2 . 2 5 2 2 . 
        . . . 5 2 . 2 . 2 . . 5 2 2 . . 
        . . . 2 . 5 . . . . 5 . 4 . . . 
        . 2 . . 5 . . . . . . . . . . . 
        . . . 5 . . . . . . . 4 . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, 50, 50)
    pause(200)
    arrow = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 4 . . . . . . . 5 . . . 
        . . . . . . . . . . . 5 . . 2 . 
        . . . 4 . 5 . . . . 5 . 2 . . . 
        . . 2 2 5 . . 2 . 2 . 2 5 . . . 
        . 2 2 5 2 . 2 5 2 2 5 2 4 5 . 5 
        2 2 5 4 5 2 5 4 5 2 5 2 4 4 5 . 
        . 2 2 5 2 . 2 5 2 . . 2 5 . . . 
        . . 2 2 5 . . 2 . . 5 . 2 . . . 
        . . . 4 . 5 . . . . . 5 . . 2 . 
        . . . . . . . . . . . . 5 . . . 
        . . . . 4 . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, -50, 50)
    pause(200)
    arrow = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . 4 . . . . 
        . . . 5 . . . . . . . . . . . . 
        . 2 . . 5 . . . . . 5 . 4 . . . 
        . . . 2 . 5 . . 2 . . 5 2 2 . . 
        . . . 5 2 . . 2 5 2 . 2 5 2 2 . 
        . 5 4 4 2 5 2 5 4 5 2 5 4 5 2 2 
        5 . 5 4 2 5 2 2 5 2 . 2 5 2 2 . 
        . . . 5 2 . 2 . 2 . . 5 2 2 . . 
        . . . 2 . 5 . . . . 5 . 4 . . . 
        . 2 . . 5 . . . . . . . . . . . 
        . . . 5 . . . . . . . 4 . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, 50, -50)
    pause(200)
    arrow = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 4 . . . . . . . 5 . . . 
        . . . . . . . . . . . 5 . . 2 . 
        . . . 4 . 5 . . . . 5 . 2 . . . 
        . . 2 2 5 . . 2 . 2 . 2 5 . . . 
        . 2 2 5 2 . 2 5 2 2 5 2 4 5 . 5 
        2 2 5 4 5 2 5 4 5 2 5 2 4 4 5 . 
        . 2 2 5 2 . 2 5 2 . . 2 5 . . . 
        . . 2 2 5 . . 2 . . 5 . 2 . . . 
        . . . 4 . 5 . . . . . 5 . . 2 . 
        . . . . . . . . . . . . 5 . . . 
        . . . . 4 . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, -50, -50)
    pause(1000)
    mySprite.startEffect(effects.trail, 500)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf2222f4e...........
        fbbbbf2222fd4...........
        .fccf45544f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff..........
        .ffefbf44fbfeff.........
        .fee41fddf14eef.........
        fdfeeddddd4eff..........
        fbffee444edd4e..........
        fbf4f2222edde....5......
        fcf.f22cccee.....4......
        .ff.f44cdc4f....5.......
        ....fffddcff....4.......
        .....fddcff....5........
        ....cddc......2.........
        ....cdc.2..5.5..........
        ....cc....2.2...........
        .........5..............
        ........................
        ........................
        ........................
        `,img`
        ........................
        ...................4....
        .......ff...........2...
        .....ff22ff.............
        ...fff2222fff......5....
        ..fff222222fff..........
        ..fff222222fff......2...
        ..feeeeeeeeeeff....5....
        .ffe22222222eff.........
        .fffffeeeefffff...4.....
        fdfefbf44fbfeff....2....
        fbfe41fddf14ef....5.....
        fbffe4dddd4efe...4......
        fcfef22222f4e....5......
        .ff4f44554f4e....2......
        ....ffffffdde...4.......
        .....ffffedde..5........
        ..........ee..4.........
        .........ccc............
        ........cc1cc...........
        .........c1c............
        .........c1c............
        .........c1c............
        .........c1c............
        `,img`
        ......ffff......4..5..5.
        ....fff22fff...5..5.4...
        ...fff2222fff....4...2..
        ..fffeeeeeefff....2.4..4
        ..ffe222222eef....42.4..
        ..fe2ffffff2ef.....22.5.
        ..ffffeeeeffff......ccc.
        .ffefbf44fbfeff....cddc.
        .ffefbf44fbfeff...cddc..
        .fee4dddddd4eef.ccddc...
        fdfeeddddd4eeffecddc....
        fbffee4444ee4fddccc.....
        fbf4f222222f1edde.......
        fcf.f222222f44ee........
        .ff.f445544f............
        ....ffffffff............
        .....ff..ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf2222f4e...........
        fbbbbf2222fd4...........
        .fccf45544f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    500,
    false
    )
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 4 . 4 . . . . . . 
        . . . . . . 4 . 5 . 4 . . . . . 
        . . . . . 4 . 5 . 5 . 4 . . . . 
        . . . . 4 . 5 . 2 . 5 . 4 . . . 
        . . . . . 5 . 2 4 2 . 5 . . . . 
        . . . . 4 . 5 . 2 . 5 . 4 . . . 
        . . . . . 4 . 5 . 5 . 4 . . . . 
        . . . . . . 4 . 5 . 4 . . . . . 
        . . . . . . . 4 . 4 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, 0, 70)
    mySprite.startEffect(effects.warmRadial, 500)
    info.changeScoreBy(1)
})
info.onLifeZero(function () {
    game.setGameOverMessage(false, "GAME OVER!")
    game.gameOver(false)
    sprites.destroy(mySprite, effects.disintegrate, 500)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.fire, 1000)
    info.changeScoreBy(1)
    enemies += -1
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    animation.runImageAnimation(
    bat,
    [img`
        . . f f f . . . . . . . . f f f 
        . f f c c . . . . . . f c b b c 
        f f c c . . . . . . f c b b c . 
        f c f c . . . . . . f b c c c . 
        f f f c c . c c . f c b b c c . 
        f f c 3 c c 3 c c f b c b b c . 
        f f b 3 b c 3 b c f b c c b c . 
        . c 1 b b b 1 b c b b c c c . . 
        . c 1 b b b 1 b b c c c c . . . 
        c b b b b b b b b b c c . . . . 
        c b 1 f f 1 c b b b b f . . . . 
        f f 1 f f 1 f b b b b f c . . . 
        f f 2 2 2 2 f b b b b f c c . . 
        . f 2 2 2 2 b b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `,img`
        . . f f f . . . . . . . . . . . 
        f f f c c . . . . . . . . f f f 
        f f c c c . c c . . . f c b b c 
        f f c 3 c c 3 c c f f b b b c . 
        f f c 3 b c 3 b c f b b c c c . 
        f c b b b b b b c f b c b c c . 
        c c 1 b b b 1 b c b b c b b c . 
        c b b b b b b b b b c c c b c . 
        c b 1 f f 1 c b b c c c c c . . 
        c f 1 f f 1 f b b b b f c . . . 
        f f f f f f f b b b b f c . . . 
        f f 2 2 2 2 f b b b b f c c . . 
        . f 2 2 2 2 2 b b b c f . . . . 
        . . f 2 2 2 b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . c c . c c . . . . . . . . 
        . . f 3 c c 3 c c c . . . . . . 
        . f c 3 b c 3 b c c c . . . . . 
        f c b b b b b b b b f f . . . . 
        c c 1 b b b 1 b b b f f . . . . 
        c b b b b b b b b c f f f . . . 
        c b 1 f f 1 c b b f f f f . . . 
        f f 1 f f 1 f b c c b b b . . . 
        f f f f f f f b f c c c c . . . 
        f f 2 2 2 2 f b f b b c c c . . 
        . f 2 2 2 2 2 b c c b b c . . . 
        . . f 2 2 2 b f f c c b b c . . 
        . . . f f f f f f f c c c c c . 
        . . . . . . . . . . . . c c c c 
        `,img`
        . f f f . . . . . . . . f f f . 
        f f c . . . . . . . f c b b c . 
        f c c . . . . . . f c b b c . . 
        c f . . . . . . . f b c c c . . 
        c f f . . . . . f f b b c c . . 
        f f f c c . c c f b c b b c . . 
        f f f c c c c c f b c c b c . . 
        . f c 3 c c 3 b c b c c c . . . 
        . c b 3 b c 3 b b c c c c . . . 
        c c b b b b b b b b c c . . . . 
        c 1 1 b b b 1 1 b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        f b c b b b c b b b b f . . . . 
        . f 1 f f f 1 b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `],
    500,
    false
    )
    animation.runImageAnimation(
    snake,
    [img`
        . . . . . c c c c c c c . . . . 
        . . . . c 6 7 7 7 7 7 6 c . . . 
        . . . c 7 c 6 6 6 6 c 7 6 c . . 
        . . c 6 7 6 f 6 6 f 6 7 7 c . . 
        . . c 7 7 7 7 7 7 7 7 7 7 c . . 
        . . f 7 8 1 f f 1 6 7 7 7 f . . 
        . . f 6 f 1 f f 1 f 7 7 7 f . . 
        . . . f f 2 2 2 2 f 7 7 6 f . . 
        . . c c f 2 2 2 2 7 7 6 f c . . 
        . c 7 7 7 7 7 7 7 7 c c 7 7 c . 
        c 7 1 1 1 7 7 7 7 f c 6 7 7 7 c 
        f 1 1 1 1 1 7 6 f c c 6 6 6 c c 
        f 1 1 1 1 1 1 6 6 c 6 6 6 c . . 
        f 6 1 1 1 1 1 6 6 6 6 6 6 c . . 
        . f 6 1 1 1 1 1 6 6 6 6 c . . . 
        . . f f c c c c c c c c . . . . 
        `,img`
        . . . . . . c c c c c c c . . . 
        . . . . . c f f 6 6 f f 7 c . . 
        . . . . c 7 6 6 6 6 6 6 7 6 c . 
        . . . c 7 7 7 7 7 7 7 7 7 7 c . 
        . . . c 7 8 1 f f 1 6 7 7 7 c . 
        . . . f 6 f 1 f f 1 f 7 7 7 f . 
        . . . f 6 f 2 2 2 2 f 7 7 7 f . 
        . . c c 6 f 2 2 2 2 f 7 7 6 f . 
        . c 7 7 7 7 2 2 2 2 7 7 f c . . 
        c 7 1 1 1 7 7 7 7 7 c c 7 7 c . 
        f 1 1 1 1 1 7 7 7 f c 6 7 7 7 c 
        f 1 1 1 1 1 1 6 f c c 6 6 6 c c 
        f 6 1 1 1 1 1 6 6 c 6 6 6 c . . 
        f 6 1 1 1 1 1 6 6 6 6 6 6 c . . 
        . f 6 1 1 1 1 6 6 6 6 6 c . . . 
        . . f f c c c c c c c c . . . . 
        `,img`
        . . . . . . c c c c c c c . . . 
        . . . . . c f f 6 6 f f 7 c . . 
        . . . . c 7 6 6 6 6 6 6 7 6 c . 
        . . . c 7 7 7 7 7 7 7 7 7 7 c . 
        . . . c 7 8 1 f f 1 6 7 7 7 c . 
        . . . f 6 f 1 f f 1 f 7 7 7 f . 
        . . . f 6 f 2 2 2 2 f 7 7 7 f . 
        . . c c 6 f 2 2 2 2 f 7 7 6 f . 
        . c 7 7 7 7 2 2 2 2 7 7 f c . . 
        c 7 1 1 1 7 7 7 7 7 c c 7 7 c . 
        f 1 1 1 1 1 7 7 7 f c 6 7 7 7 c 
        f 1 1 1 1 1 1 6 f c c 6 6 6 c c 
        f 6 1 1 1 1 1 6 6 c 6 6 6 c . . 
        f 6 1 1 1 1 1 6 6 6 6 6 6 c . . 
        . f 6 1 1 1 1 6 6 6 6 6 c . . . 
        . . f f c c c c c c c c . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . c c c c c 
        . . . . . . . . . c c 7 7 7 6 c 
        . . . . . . . . c c 7 7 7 c c . 
        . . . . . . . . c 6 7 7 c . . . 
        . . . . . . . . c 6 6 6 c . . . 
        . . . c c c c c c 6 6 6 c c . . 
        . . c 6 7 7 7 7 6 c c 6 6 6 c . 
        . c 7 7 7 7 7 7 7 7 c 6 6 6 c c 
        c 6 7 7 7 7 7 7 7 7 6 c 6 6 6 c 
        c 7 c 6 6 6 6 c 7 7 7 c 6 6 6 c 
        f 7 c c 6 6 c c 7 7 7 f 6 6 6 c 
        f 7 6 f 6 6 f 6 7 7 7 f 6 6 6 c 
        . c 1 c f f 1 c 7 6 f 6 6 c c . 
        . c c c c c c c c c c c c . . . 
        `,img`
        . . . . . . . . . . . c c c c c 
        . . . . . . . . . c c 7 7 7 6 c 
        . . . . . . . . c c 7 7 7 c c . 
        . . . . . . . . c 6 7 7 c . . . 
        . . . . . . . . c 6 6 6 c . . . 
        . . . . . . . . c 6 6 6 c c . . 
        . . . c c c c c c c 6 6 6 c c . 
        . . c 6 7 7 7 7 6 c c 6 6 6 c . 
        . c 7 7 7 7 7 7 7 7 c 6 6 6 c c 
        c 6 7 7 7 7 7 7 7 7 6 c 6 6 6 c 
        c 7 c 6 6 6 6 c 7 7 7 c 6 6 6 c 
        f 7 c c 6 6 c c 7 7 7 f 6 6 6 c 
        f 7 6 f 6 6 f 6 7 7 7 f 6 6 6 c 
        . f 7 7 7 7 7 7 7 7 6 f 6 6 c . 
        . c 1 c f f 1 c 7 6 f 6 6 c c . 
        . c c c c c c c c c c c c . . . 
        `,img`
        . . . . . . . . . . . c c c c c 
        . . . . . . . . . c c 7 7 7 6 c 
        . . . . . . . . c c 7 7 7 c c . 
        . . . . . . . . c 6 7 7 c . . . 
        . . . . . . . . c 6 6 6 c . . . 
        . . . . . . . . c 6 6 6 c c . . 
        . . . c c c c c c c 6 6 6 c c . 
        . . c 6 7 7 7 7 6 c c 6 6 6 c . 
        . c 7 7 7 7 7 7 7 7 c 6 6 6 c c 
        c 6 7 7 7 7 7 7 7 7 6 c 6 6 6 c 
        c 7 c 6 6 6 6 c 7 7 7 c 6 6 6 c 
        f 7 c c 6 6 c c 7 7 7 f 6 6 6 c 
        f 7 6 f 6 6 f 6 7 7 7 f 6 6 6 c 
        . f 7 7 7 7 7 7 7 7 6 f 6 6 c . 
        . c 1 c f f 1 c 7 6 f 6 6 c c . 
        . c c c c c c c c c c c c . . . 
        `],
    500,
    false
    )
    animation.runImageAnimation(
    skeleton,
    [img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .....fffc1111111f.......
        ...fc111cd1111111f......
        ...f1b1b1b1111dddf......
        ...fbfbffcf11fcddf......
        ......fcf111111bbf......
        .......ccbdb1b1fcf......
        .......fffbfbfdff.......
        ........ffffffff........
        ........fffffffffff.....
        .........fffffc111cf....
        .........fffff1b1b1f....
        ..........ffffbfbfbf....
        ...........ffff.........
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ....7.fd11111111df......
        ...7..fd11111111df......
        ...7..fd11111111df......
        ...7..fddd1111dddff.....
        ...77.fbdbfddfbdbfcf....
        ...777fcdcf11fcdcfbf....
        ....77fffbdb1bdffcf.....
        ....fcb1bcffffff........
        ....f1c1c1ffffff........
        ....fdfdfdfffff.........
        .....f.f.f..............
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd111111111f......
        ......fd11111111df......
        ......fd11111111df......
        ......fcdd1111ddcff.....
        .......fbcf11fcbfbbf....
        .......ffbdb1bdffff.....
        ........fcbfbfdf........
        ........ffffffff........
        ......ffffffffff........
        .....fcb1bcffff.........
        ......ffbff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fdd111111ddf......
        ......fbdd1111dddf......
        ......fcdbfddfbdbf......
        .......fbcf11fcbfff.....
        .......ffb1111bcfbcf....
        ........fcdb1bdfbbbf....
        .......ffffffffffcf.....
        .....fcb1bcfffff........
        .....f1b1b1ffff.........
        ......ffbff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    500,
    false
    )
    animation.runImageAnimation(
    dragon,
    [img`
        ........................
        ........................
        ..........ccc...........
        .........cccc...........
        .....ccccccc..ccc.......
        ...cc555555cccccc.......
        ..c5555555555bcc........
        .c555555555555b..cc.....
        c555551ff555555bccc.....
        c55d55ff55555555bc......
        c5555555555555555b......
        .cbb31bb5555dd555b.cc...
        .c5333b555ddddd55dccc...
        .c533b55ddddddddddb.....
        .c5555dddbb55bdddddccc..
        ..ccccbbbb555bdddddccc..
        ...cdcbc5555bddddddcc...
        ....ccbc55bc5ddddddbcccc
        .....cbbcc5555dddddddddc
        .....ccbbb555ddbddddddc.
        .....cdcbc55ddbbbdddcc..
        ...ccdddccddddbcbbcc....
        ...ccccccd555ddccc......
        ........cccccccc........
        `,img`
        ............ccc.........
        .......cccccccc.........
        .....cc55555cc..cc......
        ....c555555555cccc......
        ...c55555555555bcc......
        ..c555551ff55555b..cc...
        ..c55d55ff5555555bccc...
        ..c55555555d55555bcc....
        ..c5555d5555d55555b.....
        ..cbbbb55555ddd555b.cc..
        ..c555d5555ddddd55dccc..
        ...c555dbbbdddbd5ddcc...
        ....cccbbbbb555bdddb....
        ....cbbbbbbc555bdddccc..
        ...cbbbbbbc555bddddcc...
        ...cbbbbbc555bdddddc....
        ..ccbbbbbc55bddddddcc...
        ..ccbbbbbbcb55dddddbcc..
        ...cbbbbbb5555ddddddddcc
        ....cbbbbb555ddbdddddddc
        ....cccbbc55ddbbbddddcc.
        ...ccdddccddddbcbbccc...
        ...ccccccd555ddccc......
        ........cccccccc........
        `,img`
        .............ccc........
        ........cccccccc........
        ......cc55555cc..cc.....
        .....c555555555cccc.....
        ....c55555555555bcc.....
        ...c555555ccb5555b.cc...
        ...c55d55c55555555bcc...
        ...c55555555dd5555bc....
        ...c5555d5555dd5555.....
        ...cbbbd555555dd555.cc..
        ...c555d555555ddd55ccc..
        ....c555d5555ddbd5dcc...
        ....cccbbbbb555bdddb....
        ...cbbbbbbbc555bdddccc..
        ..cbbbbbbbc555bddddcc...
        ..cbbbbbbc555bdddddc....
        .ccbbbbbbc55bddddddcc...
        .ccbbbbbbbcb55dddddbc...
        ..cbbbbbbb5555ddddddbc..
        ...cbbbbbb555ddbddddddc.
        ....cccbbc55ddbbbddddddc
        ...ccdddccddddbcbbcccccc
        ...ccccccd555ddccc......
        ........cccccccc........
        `,img`
        ........................
        ........................
        ........................
        ..........ccc...........
        .........cccc...........
        .....ccccccc..ccc.......
        ...cc555555cccccc.......
        ..c5555555555bcc........
        .c555555555555b..cc.....
        c555555ccb55555bccc.....
        c55d55c555555555bc......
        c5555555555555555b......
        .cbbb1bb5555dd555b.cc...
        .c533bbbb5ddddd55dcc....
        .c533bbbb5ddddddddbcc...
        .c533bbb55dddddddddcccc.
        .c5333bb5bb55bdddddcccdc
        .c5333b5bb555bddddddbddc
        .c53335b5555bddddddddddc
        ..c5555c55bb55dbddddddcc
        ...cccbccc55ddbbbddddcc.
        ....cdddccddddbcbbbcc...
        ....cccccd555ddcccc.....
        ........cccccccc........
        `,img`
        ........................
        ........................
        ........................
        ..........ccc...........
        .........cccc...........
        .....ccccccc..ccc.......
        ...cc555555cccccc.......
        ..c5555555555bcc........
        .c555555555555b..cc.....
        c555555ccb55555bccc.....
        c55d55c555555555bc......
        c5555555555555555b......
        .cbbb1bb5555dd555b.cc...
        .c533bbbb5ddddd55dcc....
        .c533bbbb5ddddddddbcc...
        .c5333bb55dddddddddcccc.
        .c5333b55bb55bdddddcccdc
        .c533355bb555bddddddbddc
        ..c5555b5555bddddddddddc
        ...cccbc55bb55dbddddddcc
        .....cbbcc55ddbbbddddcc.
        ....cdddccddddbcbbbcc...
        ....cccccd555ddcccc.....
        ........cccccccc........
        `,img`
        ........................
        ........................
        ........................
        ..........ccc...........
        .........cccc...........
        .....ccccccc..ccc.......
        ...cc555555cccccc.......
        ..c5555555555bcc........
        .c555555555555b..cc.....
        c555555ccb55555bccc.....
        c55d55c555555555bc......
        c5555555555555555b......
        .cbbb1bb5555dd555b.cc...
        .c533bbb55ddddd55dcc....
        .c5333bb5dddddddddbcc...
        .c5333b55ddddddddddcccc.
        .c533355dbb55bdddddcccdc
        ..c55555bb555bddddddbddc
        ...cccbb5555bddddddddddc
        .....cbc55bb55dbddddddcc
        .....cdbcc55ddbbbddddcc.
        ....cdddccddddbcbbbcc...
        ....cccccd555ddcccc.....
        ........cccccccc........
        `],
    500,
    false
    )
    mySprite.startEffect(effects.ashes, 500)
    scene.cameraShake(4, 500)
    pause(100)
    info.changeLifeBy(-1)
    pause(1000)
})
let random_loc_4 = 0
let random_loc_3 = 0
let random_loc_2 = 0
let random_loc_1 = 0
let dragon: Sprite = null
let skeleton: Sprite = null
let snake: Sprite = null
let bat: Sprite = null
let projectile: Sprite = null
let arrow: Sprite = null
let mySprite: Sprite = null
music.play(music.stringPlayable("G F G A - F E D ", 120), music.PlaybackMode.LoopingInBackground)
info.setLife(3)
let enemies = 4
let otherSprite = [
img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `,
img`
    . f f f . . . . . . . . f f f . 
    f f c . . . . . . . f c b b c . 
    f c c . . . . . . f c b b c . . 
    c f . . . . . . . f b c c c . . 
    c f f . . . . . f f b b c c . . 
    f f f c c . c c f b c b b c . . 
    f f f c c c c c f b c c b c . . 
    . f c 3 c c 3 b c b c c c . . . 
    . c b 3 b c 3 b b c c c c . . . 
    c c b b b b b b b b c c . . . . 
    c b 1 b b b 1 b b b b f c . . . 
    f b b b b b b b b b b f c c . . 
    f b c b b b c b b b b f . . . . 
    . f 1 f f f 1 b b b c f . . . . 
    . . f b b b b b b c f . . . . . 
    . . . f f f f f f f . . . . . . 
    `,
img`
    . . . c c c c c . . . . . . . . 
    . . c 7 7 c c c c c . . . . . . 
    . c c 7 c c c c c c c . . . . . 
    . c c c c c c c c . c . . . . . 
    . c c c c c . . . . c . . . . . 
    . . f c f . . . . c c . . . . . 
    . . f . f . . c c c . . . . . . 
    . . . . . . c c . . . . c c . . 
    . . . . c c c c . . . c c . c . 
    . . . c c c c b b b b . . c c c 
    . . c c c c b c c c c b b b c c 
    . . c c c c b c b b c c b b c c 
    . . c c c c c b b b b b c c c c 
    . . . c c c c . c c c c c c c . 
    . . . . . c c c c c c c c . . . 
    . . . . . . . . . . . . . . . . 
    `,
img`
    . . . . . c c c c c c c . . . . 
    . . . . c 6 7 7 7 7 7 6 c . . . 
    . . . c 7 c 6 6 6 6 c 7 6 c . . 
    . . c 6 7 6 f 6 6 f 6 7 7 c . . 
    . . c 7 7 7 7 7 7 7 7 7 7 c . . 
    . . f 7 8 1 f f 1 6 7 7 7 f . . 
    . . f 6 f 1 f f 1 f 7 7 7 f . . 
    . . . f f 2 2 2 2 f 7 7 6 f . . 
    . . c c f 2 2 2 2 7 7 6 f c . . 
    . c 7 7 7 7 7 7 7 7 c c 7 7 c . 
    c 7 1 1 1 7 7 7 7 f c 6 7 7 7 c 
    f 1 1 1 1 1 7 6 f c c 6 6 6 c c 
    f 1 1 1 1 1 1 6 6 c 6 6 6 c . . 
    f 6 1 1 1 1 1 6 6 6 6 6 6 c . . 
    . f 6 1 1 1 1 1 6 6 6 6 c . . . 
    . . f f c c c c c c c c . . . . 
    `
]
mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f f f f d d d d d e e f . . 
    . f d d d d f 4 4 4 e e f . . . 
    . f b b b b f 2 2 2 2 f 4 e . . 
    . f b b b b f 2 2 2 2 f d 4 . . 
    . . f c c f 4 5 5 4 4 f 4 4 . . 
    . . . f f f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
mySprite.setBounceOnWall(true)
controller.moveSprite(mySprite)
mySprite.setVelocity(0, 0)
animation.runImageAnimation(
mySprite,
[img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f f f f d d d d d e e f . . 
    . f d d d d f 4 4 4 e e f . . . 
    . f b b b b f 2 2 2 2 f 4 e . . 
    . f b b b b f 2 2 2 2 f d 4 . . 
    . . f c c f 4 5 5 4 4 f 4 4 . . 
    . . . f f f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . f f e 2 f f f f f f 2 e f f . 
    . f f f f f e e e e f f f f f . 
    . . f e f b f 4 4 f b f e f . . 
    . f f e 4 1 f d d f 1 4 e f . . 
    f d f f e 4 d d d d 4 e f e . . 
    f b f e f 2 2 2 2 e d d 4 e . . 
    f b f 4 f 2 2 2 2 e d d e . . . 
    f c f . f 4 4 5 5 f e e . . . . 
    . f f . f f f f f f f . . . . . 
    . . . . f f f . . . . . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f e e 2 2 2 2 2 2 e f f . . 
    . f f e 2 f f f f f f 2 e f f . 
    . f f f f f e e e e f f f f f . 
    . . f e f b f 4 4 f b f e f . . 
    . . f e 4 1 f d d f 1 4 e f . . 
    . . e f f f f d d d 4 e f . . . 
    . . f d d d d f 2 2 2 f e f . . 
    . . f b b b b f 2 2 2 f 4 e . . 
    . . f b b b b f 5 4 4 f . . . . 
    . . . f c c f f f f f f . . . . 
    . . . . f f . . . f f f . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f e e 2 2 2 2 2 2 e f f . . 
    . f f e 2 f f f f f f 2 e f f . 
    . f f f f f e e e e f f f f f . 
    . . f e f b f 4 4 f b f e f . . 
    . . f e 4 1 f d d f 1 4 e f f . 
    . . e f e 4 d d d d 4 e f f d f 
    . . e 4 d d e 2 2 2 2 f e f b f 
    . . . e d d e 2 2 2 2 f 4 f b f 
    . . . . e e f 5 5 4 4 f . f c f 
    . . . . . f f f f f f f . f f . 
    . . . . . . . . . f f f . . . . 
    `],
500,
true
)
scene.setBackgroundImage(img`
    ddddddbddddfddddddddddfddddddddfdddbdddfddbddfddddfddbddfddddbdddfdddbdddfdddddfddddfdddddbddffdddddbdddfdddddbdddfdddddddddddfddddbddddfddddbdddfdddddb777ddddd
    ddddddbddddfddddbdddddfddddbdddfdddbdddfddbddfddbdfddbddfddddbdddfdddbdddfdddddfdbddfdddddbdddfdddddbdddfdddddbdddfddddddbddddfddddbddddfddddbdddfdd777777777ddd
    ddddddbddddfddddbdddddfddddbdddfdddbdddfddbddfddbdfddbddfddddbdddfdddbdddfdddddfdbddfdddddbdddfdddddbdddfdddddbdddfddddddbddddfddddbddddfddddbdddfd777777777777d
    ddddddbddddfddddbdddddfddddbdddfdddbdddfddbddfddbdfddbddfddddbdddfdddbdddfdddddfdbddfdddddbdddfdddddbdddfdddddbdddfddddddbddddfdddddbdddfddddbddddf77dd7bd7d777d
    ddd77777777dddddbddddfdddddbdddfdddbdddfddbddfddbdfddbddfddddbdddfdddbdddfdddddfdbddfdddddbdddfdddddbdddfdddddbddddfdddddbdddddfddddbddddfddddbdddf777777d7d7d77
    dd777777d777dddbdddddfddddbdddfdddbdddfdddbddfddbdfddbddfddddbdddfdddbdddfdddddfdbddfdddddbdddfddddddbdddfdddddbdddfddddddbddddfddddbddddfddddbdddfd777777777d77
    d777d7777df77ddbdddddfddddbdddfdddbdddfddbdddfddbdfddbddfddddbdddfdddbdddfdddddfdbddfdddddbdddfddddddbdddfdddddbdddfddddddbddddfddddbddddfddddbddddf77777777777d
    d7d7db7dd7777ddbdddddfddddbdddfdddbdddfddbddfdddbdfddbddfddddbdddfdddbdddfdddddfdbdddfdddddbdddfdddddbdddfdddddbdddfddddddbddddfdddddbdddfdddddbdddf77ddee7777dd
    7d77777dd77777dbdddddfddddbdddfdddbdddfddbddfdddbdfddbddfddddbdddfdddbdddfdddddfddbddfdddddbdddfdddddbdddfdddddbddddfdddddbdddddfddddbddddfddddbdddfd7777e777ddd
    7777777777d7777dddddfddddbdddfdddbddddfddbddfdddbdfddbddfddddbdddfdddbdddfdddddfddbddfdddddbdddfdddddbddddfdddddbdddfddddddbddddfddddbddddfddddbddddfddded7bdddd
    d77777d777d77d7dddddfddddbdddfdddbddddfddbddfddbddfddbddfddddbdddfdddbdddfdddddfddbddfdddddbdddfddddddbdddfdddddbdddfddddddbddddfdddddbdddfddddbddddfddeedebdddd
    d77d77dd777777bdddddfddddbdddfdddbdddfdddbddfddbddfddbddfddddbdddfdddbdddfdddddfddbddfdddddbdddfddddddbdddfdddddbdddfddddddbddddfdddddbddddfddddbdddfddeededbddd
    d77eb777777777bdddddfddddbdddfdddbdddfddbdddfddbddfddbddfddddbdddfdddbdddfdddddfddbddfdddddbdddfddddddbdddfdddddbddddfddddddbddddfddddbddddfddddbddddfdeeeedbddd
    777ed77777777bdddddfddddbdddfddddbdddfddbddfdddbddfddbddfddddbdddfdddbdddfdddddfddbddfddddddbdddfdddddbdddfdddddbddddfddddddbddddfdddddbdddfddddbddddfdeeeedbddd
    77de7777f7777bdddddfddddbdddfdddbddddfddbddfdddbddfddbddfddddbdddfdddbdddfdddddfddbdddfdddddbdddfdddddbddddfdddddbdddfddddddbddddfdddddbddddfddddbdddfdedeeddbdd
    d7777777e777dbdddddfddddbdddfdddbddddfddbddfdddbddfddbddfddddbdddfdddbdddfdddddfddbdddfdddddbdddfdddddbddddfdddddbdddfddddddbdddddfddddbddddfddddbddddfeedeeebdd
    dd7be777e77ddbdddddfddddbdddfdddbdddfdddbddfdddbddfddbddfddddbdddfdddbdddfdddddfdddbddfdddddbdddfddddddbdddfdddddbddddfddddddbddddfddddbddddfddddbddddeeedeeedbd
    ddbdd7e7eddddbddddfddddbdddfddddbdddfdddbddfdddbdfdddbddfddddbdddfdddbdddfdddddfdddbddfdddddbdddfddddddbdddfdddddbddddfddddddbddddfdddddbdddfddddbddddedddddddbd
    ddbddeefedddbdddddfddddbdddfdddbddddfddbdddfdddbdfdddbddfddddbdddfdddbdddfdddddfdddbddfdddddbdddfddddddbdddfddddddbdddfddddddbddddfdddddbddddfddddbddddfdddddddb
    ddbddeefedddbdddddfddddbdddfdddbddddfddbdddfddbddfdddbddfddddbdddfdddbdddfdddddfdddbddfdddddbddddfdddddbddddfdddddbdddfddddddbdddddfddddbddddfddddbddddfdddddddd
    ddbddeeeedddbdddddfddddbddfddddbddddfddbddfdddbddfdddbddfddddbdddfdddbdddfdddddfdddbddfddddddbdddfdddddbddddfdddddbddddfddddddbddddfdddddbdddfddddbddddfdddddddd
    dbdddeeeedddbdddddfdddbdddfddddbddddfddbddfdddbddfdddbddfddddbdddfdddbdddfdddddfdddbdddfdddddbdddfddddddbdddfdddddbddddfddddddbddddfdddddbddddfddddbdddfdddddddd
    dbdddeeeeedbdddddfddddbdddfddddbdddfdddbddfdddbddfdddbddfddddbdddfdddbdddfdddddfdddbdddfdddddbdddfddddddbdddfdddddbddddfddddddbddddfdddddbddddfddddbddddfddddddd
    dbdddeeeeedbdddddfddddbdddfdddbddddfdddbddfdddbddfdddbddfddddbdddfdddbdddfdddddfddddbddfdddddbdddfddddddbddddfdddddbdddfddddddbdddddfddddbddddfddddbddddfddddddd
    dbddeeeeeeebdddddfddddbddfddddbddddfddbdddfdddbddfddbdddfddddbdddfddddbddfddddddfdddbddfdddddbdddfddddddbddddfdddddbddddfddddddbddddfdddddbddddfdddbddddfddddddd
    bddeefddedebdddddfdddbdddfddddbddddfddbdddfdddbddfddbdddfddddbdddfddddbddfddddddfdddbddfdddddbddddfdddddbddddfdddddbddddfddddddbddddfdddddbddddfddddbddddfdddddd
    dddddfddddbdddddfddddbdddfddddbddddfddbddfddddbddfddbdddfddddbdddfddddbddfddddddfdddbddfddddddbdddfddddddbdddfdddddbddddfddddddbddddfdddddbddddfddddbddddfdddddd
    dddddfddddbdddddfddddbdddfdddbddddfdddbddfddddbddfddbdddfddddbdddfddddbddfddddddfdddbddfddddddbdddfddddddbdddfddddddbdddfddddddbdddddfdddddbddddfdddbddddfdddddd
    dddddfddddbdddddfddddbddfddddbddddfdddbddfdddbdddfddbdddfddddbdddfddddbddfddddddfdddbdddfdddddbdddfddddddbddddfdddddbddddfddddddbddddfdddddbddddfddddbddddfddddd
    ddddfdddddbdddddfdddbdddfddddbddddfdddbddfdddbdddfddbdddfddddbdddfddddbddfddddddfdddbdddfdddddbdddfddddddbddddfdddddbddddfddddddbddddfdddddbddddfddddbddddfddddd
    ddddfddddbddddddfdddbdddfddddbddddfddbdddfdddbdddfddbddddfdddbdddfddddbddfddddddfdddbdddfdddddbdddfddddddbddddfdddddbddddfddddddbddddfddddddbdddfddddbddddfddddd
    ddddfddddbdddddfddddbdddfddddbddddfddbdddfdddbdddfddbddddfdddbdddfddddbddfddddddfddddbddfdddddbddddfddddddbdddfdddddbddddfdddddddbddddfdddddbddddfdddbdddddfdddd
    ddddfddddbdddddfddddbddfddddbddddfdddbdddfdddbdddfddbddddfdddbdddfddddbddfddddddfddddbddfdddddbddddfddddddbdddfddddddbddddfddddddbddddfdddddbddddfddddbddddfdddd
    dddfdddddbdddddfdddbdddfddddbddddfdddbddfddddbdddfddbddddfdddbdddfddddbddfddddddfddddbddfddddddbdddfddddddbddddfdddddbddddfddddddbddddfdddddbddddfddddbddddfdddd
    dddfddddbddddddfdddbdddfddddbddddfdddbddfddddbddfdddbddddfdddbdddfddddbddfddddddfddddbddfddddddbdddfddddddbddddfdddddbddddfddddddbddddfddddddbddddfdddbdddddfddd
    dddfddddbdddddfddddbdddfddddbddddfdddbddfddddbddfdddbddddfdddbdddfddddbddfddddddfddddbdddfdddddbdddfddddddbddddfdddddbddddfdddddddbddddfdddddbddddfddddbddddfddd
    dddfddddbdddddfddddbddfdddddbddddfddbdddfddddbddfdddbddddfdddbdddfddddbddfddddddfddddbdddfdddddbddddfddddddbdddfdddddbdddddfddddddbddddfdddddbddddfddddbddddfddd
    dddfddddbdddddfdddbdddfddddbdddddfddbdddfdddbdddfdddbddddfdddbdddfddddbddfddddddfddddbdddfdddddbddddfddddddbddddfdddddbddddfddddddbddddfddddddbddddfdddbdddddfdd
    ddfddddbddddddfdddbdddfddddbddddfdddbdddfdddbdddfdddbddddfdddbdddfddddbddfddddddfdddddbddfdddddbddddfddddddbddddfdddddbddddfddddddbdddddfdddddbddddfdddbdddddfdd
    ddfddddbdddddfddddbdddfddddbddddfdddbdddfdddbdddfdddbddddfdddbdddfddddbddfddddddfdddddbddfdddddbddddfddddddbddddfdddddbddddfdddddddbddddfdddddbddddfddddbddddfdd
    ddfddddbdddddfddddbddfdddddbddddfdddbddfddddbdddfdddbddddfdddbdddfddddbddfddddddfdddddbddfddddddbdddfddddddbddddfdddddbdddddfddddddbddddfddddddbdddfddddbdddddfd
    ddfddddbdddddfdddbdddfddddbdddddfdddbddfddddbdddfdddbddddfdddbdddfddddbddfddddddfdddddbddfddddddbdddfdddddddbdddfddddddbddddfddddddbddddfddddddbddddfdddbdddddfd
    dfddddbddddddfdddbdddfddddbdddddfddbdddfddddbdddfdddbddddfdddbdddfddddbddfddddddfdddddbdddfdddddbddddfddddddbddddfdddddbddddfddddddbdddddfdddddbddddfddddbddddfd
    dfddddbddddddfdddbdddfddddbddddfdddbdddfddddbdddfdddbddddfdddbdddfddddbddfddddddfdddddbdddfdddddbddddfddddddbddddfdddddbddddfdddddddbddddfdddddbddddfddd7777777f
    dfddddbdddddfddddbddfdddddbddddfdddbdddfddddbdddfdddbddddfdddbdddfddddbddfddddddfdddddbdddfdddddbddddfddddddbddddfdddddbdddddfddddddbddddfddddddbddddf77777d7dd7
    dfddddbdddddfdddbdddfdddddbddddfdddbdddfddddbdddfdddbddddfdddbdddfddddbddfddddddfddddddbddfdddddbddddfddddddbddddfdddddbdddddfddddddbddddfddddddbdddd7777777777d
    fddddbddddddfdddbdddfddddbdddddfdddbddfddddbddddfdddbddddfdddbdddfddddbddfddddddfddddddbddfddddddbdddfddddddbddddfddddddbddddfddddddbdddddfdddddbdddd77777b7777d
    dddddbddddddfdddbdddfddddbdddddfdddbddfddddbddddfdddbddddfdddbdddfddddbddfddddddfddddddbddfddddddbdddfdddddddbddddfdddddbddddfdddddddbddddfddddddbdd77fdd7bdd777
    dddddbdddddfddddbddfdddddbdddddfddbdddfddddbddddfddbdddddfdddbdddfdddddbdfdddddddfdddddbddfddddddbddddfddddddbddddfdddddbdddddfddddddbddddfddddddbdd77777777d777
    dddddbdddddfdddbdddfdddddbddddfdddbdddfddddbddddfddbdddddfdddbdddfdddddbdfdddddddfdddddbdddfdddddbddddfddddddbddddfdddddbdddddfddddddbddddfddddddbdd7d77777b7777
    dddddb777ddfdddbdddfddddbdddddfdddbdddfddddbddddfddbdddddfdddbdddfdddddbdfdddddddfdddddbdddfdddddbddddfddddddbddddfddddddbddddfdddddddbddddfddddddb77d7777777777
    ddd7777d77dfdddbdddfddddbdddddfdddbdddfddddbdddfdddbdddddfdddbdddfdddddbdfdddddddfdddddbdddfdddddbddddfddddddbdddddfdddddbddddfdddddddbddddfddddddbd777fee777777
    ddd7777d77777ddbddfdddddbdddddfdddbdddfddddbdddfdddbdddddfdddbdddfdddddbdfdddddddfdddddbdddfdddddbddddfdddddddbddddfdddddbdddddfddddddbddddfddddddbdd7777ee7777d
    d777bdd7777d77bdddfdddddbdddddfdddbddfdddddbdddfdddbdddddfdddbdddfdddddbdfdddddddfddddddbddfddddddbdddfdddddddbddddfdddddbdddddfddddddbddddfddddddbddd77ee7777dd
    77d7777d777777bdddfdddddbddddfdddbdddfdddddbdddfdddbdddddfdddbdddfdddddbdfdddddddfddddddbddfddddddbddddfddddddbddddfdddddbdddddfdddddddbddddfddddddbddd777eebddd
    7d7777d77777777dddfddddbdddddfdddbdddfddddbddddfdddbdddddfdddbdddfdddddbdfdddddddfddddddbddfddddddbddddfddddddbddddfddddddbddddfdddddddbddddfddddddbddddeedebddd
    7777d7d77777d7bddfdddddbdddddfdddbdddfddddbddddfdddbdddddfdddbdddfdddddbdfdddddddfddddddbdddfdddddbddddfddddddbdddddfdddddbdddddfddddddbddddfddddddbddddeeeedbdd
    777777d7777777bddfdddddbdddddfdddbdddfddddbddddfdddbdddddfdddbdddfdddddbdfdddddddfddddddbdddfdddddbddddfdddddddbddddfdddddbdddddfddddddbddddfdddddddbdddefeedbdd
    77777d777777777ddfdddddbdddddfdddbdddfddddbddddfdddbdddddfdddbdddfdddddbdfdddddddfddddddbdddfdddddbddddfdddddddbddddfdddddbdddddfdddddddbddddfddddddbddeefeedbdd
    77777d777f777b7dfdddddbddddddfdddbddfdddddbddddfdddbdddddfdddbdddfdddddbdfdddddddfddddddbdddfddddddbdddfdddddddbddddfddddddbddddfdddddddbddddfddddddbddededeebdd
    777777d77f77777dfdddddbdddddfdddbdddfdddddbddddfdddbddddddfddbdddfdddddbddfddddddfdddddddbddfddddddbddddfddddddbddddfddddddbdddddfddddddbddddfdddddddbdeeefdedbd
    d77d77ed777777ddfdddddbdddddfdddbdddfdddddbddddfdddbddddddfddbdddfdddddbddfddddddfdddddddbddfddddddbddddfddddddbdddddfdddddbdddddfddddddbdddddfddddddbdeddfdddbd
    d777dded777777ddfdddddbdddddfdddbdddfdddddbddddfdddbddddddfddbdddfdddddbddfddddddfdddddddbddfddddddbddddfdddddddbddddfdddddbdddddfdddddddbddddfddddddbddddfdddbd
    d7777ded77777ddfddddddbdddddfdddbdddfdddddbddddfdddbddddddfddbdddfdddddbddfddddddfdddddddbdddfdddddbddddfdddddddbddddfdddddbddddddfddddddbddddfddddddbddddfddddb
    db777ded7777bddfdddddbddddddfdddbdddfdddddbddddfdddbddddddfddbdddfdddddbddfddddddfdddddddbdddfdddddbddddfdddddddbddddfddddddbdddddfddddddbddddfdddddddbddddfdddd
    dbdd77efedddbddfdddddbdddddfdddbddddfddddbdddddfdddbddddddfddbdddfdddddbddfddddddfdddddddbdddfdddddbddddfdddddddbddddfddddddbdddddfddddddbdddddfddddddbddddfdddd
    dbdddeefeddbdddfdddddbdddddfdddbdddfdddddbdddddfdddbddddddfddbdddfdddddbddfddddddfdddddddbdddfddddddbddddfddddddbdddddfdddddbdddddfdddddddbddddfddddddbddddfdddd
    bddddeefeddbddfddddddbdddddfdddbdddfdddddbdddddfdddbddddddfddbdddfdddddbddfddddddfddddddddbddfddddddbddddfdddddddbddddfdddddbddddddfddddddbddddfdddddddbddddfddd
    dddddeefeddbddfddddddbdddddfdddbdddfdddddbddddfddddbddddddfddbdddfdddddbddfddddddfddddddddbddfddddddbddddfdddddddbddddfdddddbddddddfddddddbddddfdddddddbddddfddd
    dddddeefeddbddfdddddbddddddfdddbdddfdddddbddddfddddbddddddfddbdddfdddddbddfddddddfddddddddbddfddddddbddddfdddddddbddddfddddddbdddddfddddddbdddddfddddddbddddfddd
    ddddeeeeedbdddfdddddbdddddfddddbdddfdddddbddddfddddbddddddfddbdddfdddddbddfddddddfddddddddbdddfdddddbddddfdddddddbdddddfdddddbdddddfdddddddbddddfddddddbdddddfdd
    ddddeeeeeebddfddddddbdddddfdddbddddfdddddbddddfdddbdddddddfddbdddfddddddbdfdddddddfdddddddbdddfdddddbddddfdddddddbdddddfdddddbddddddfddddddbddddfdddddddbddddfdd
    ddddeeeedebddfddddddbdddddfdddbddddfdddddbddddfdddbdddddddfddbdddfddddddbdfdddddddfdddddddbdddfdddddbdddddfdddddddbddddfdddddbddddddfddddddbddddfdddddddbddddfdd
    dddeeeeeeebddfdddddbddddddfdddbdddfddddddbddddfdddbdddddddfddbdddfddddddbdfdddddddfdddddddbdddfddddddbddddfdddddddbddddfddddddbdddddfdddddddbddddfddddddbddddfdd
    dddededdeeeddfdddddbddddddfdddbdddfdddddbdddddfdddbdddddddfddbdddfddddddbdfdddddddfdddddddbdddfddddddbddddfdddddddbddddfddddddbdddddfdddddddbddddfdddddddbddddfd
    dddedfddeeddfddddddbddddddfdddbdddfdddddbdddddfdddbdddddddfddbdddfddddddbdfdddddddfddddddddbddfddddddbddddfdddddddbdddddfdddddbddddddfddddddbddddfdddddddbddddfd
    dddddfdddbddfddddddbdddddfddddbdddfdddddbdddddfdddbdddddddfddbdddfddddddbdfdddddddfddddddddbddfddddddbddddfdddddddbdddddfdddddbddddddfddddddbddddfdddddddbddddfd
    dddddfdddbddfddddddbdddddfdddbddddfdddddbdddddfdddbdddddddfddbdddfddddddbdfdddddddfddddddddbdddfdddddbddddfdddddddbdddddfdddddbddddddfdddddddbddddfdddddddbddddf
    dddddfddbdddfdddddbddddddfdddbddddfdddddbdddddfdddbdddddddfddbdddfddddddbdfdddddddfddddddddbdddfdddddbdddddfdddddddbddddfddddddbdddddfdddddddbddddfdddddddbddddd
    ddddfdddbddfddddddbddddddfdddbdddfddddddbdddddfdddbdddddddfddbdddfddddddbdfdddddddfddddddddbdddfddddddbddddfdddddddbddddfddddddbddddddfddddddbddddfdddddddbddddd
    ddddfdddbddfddddddbddddddfdddbdddfddddddbdddddfdddbdddddddfddbdddfddddddbdfdddddddfddddddddbdddfddddddbddddfdddddddbdddddfdddddbddddddfddddddbddddfdddddddbddddd
    ddddfdddbddfddddddbdddddfddddbdddfddddddbdddddfdddbdddddddfddbdddfddddddbdfdddddddfddddddddbdddfddddddbddddfdddddddbdddddfdddddbddddddfdddddddbddddfdddddddbdddd
    ddddfddbdddfdddddbddddddfddddbdddfddddddbdddddfdddbdddddddfddbdddfddddddbdfdddddddfdddddddddbddfddddddbddddfdddddddbdddddfddddddbdddddfdddddddbddddfdddddddbdddd
    dddfdddbddfddddddbddddddfdddbddddfdddddbddddddfdddbdddddddfddbdddfddddddbdfdddddddfdddddddddbddfddddddbddddfddddddddbddddfddddddbddddddfddddddbddddfdddddddbdddd
    dddfdddbddfddddddbddddddfdddbddddfdddddbddddddfdddbdddddddfddbdddfddddddbdfdddddddfdddddddddbdddfdddddbdddddfdddddddbdddddfdddddbddddddfddddddbdddddfdddddddbddd
    dddfdddbddfddddddbddddddfdddbddddfdddddbdddddfddddbdddddddfddbdddfddddddbdfdddddddfdddddddddbdddfdddddbdddddfdddddddbdddddfdddddbddddddfdddddddbddddfdddddddbddd
    dddfddbdddfddddddbddddddfdddbdddfddddddbdddddfddddbdddddddfddbdddfddddddbdfdddddddfdddddddddbdddfddddddbddddfdddddddbdddddfdddddbddddddfdddddddbddddfdddddddbddd
    ddfdddbddfddddddbddddddfddddbdddfddddddbdddddfddddbdddddddfddbdddfddddddbdfdddddddfdddddddddbdddfddddddbddddfdddddddbdddddfddddddbddddddfddddddbddddfddddddddbdd
    ddfdddbddfddddddbddddddfddddbdddfddddddbdddddfddddbdddddddfddbdddfddddddbdfdddddddfdddddddddbdddfddddddbddddfddddddddbddddfddddddbddddddfddddddbdddddfdddddddbdd
    ddfdddbddfddddddbddddddfdddbddddfddddddbdddddfddddbddddddddfdbdddfddddddbdfdddddddfdddddddddbdddfddddddbddddfddddddddbdddddfdddddbddddddfdddddddbddddfdddddddbdd
    ddfddbdddfddddddbddddddfdddbddddfddddddbdddddfddddbddddddddfdbdddfddddddbdfdddddddfddddddddddbddfddddddbdddddfdddddddbdddddfdddddbddddddfdddddddbddddfdddddddbdd
    ddfddbddfdddddddbddddddfdddbddddfddddddbdddddfddddbddddddddfdbdddfddddddbdfdddddddfddddddddddbdddfdddddbdddddfdddddddbdddddfdddddbdddddddfddddddbddddfddddddddbd
    dfdddbddfddddddbddddddfddddbddddfdddddbddddddfddddbddddddddfdbdddfddddddbdfdddddddfddddddddddbdddfdddddbdddddfdddddddbdddddfddddddbddddddfdddddddbddddfdddddddbd
    dfdddbddfddddddbddddddfddddbdddfddddddbddddddfddddbddddddddfdbdddfddddddbdfdddddddfddddddddddbdddfddddddbddddfddddddddbddddfddddddbddddddfdddddddbddddfdddddddbd
    dfddbdddfddddddbddddddfddddbdddfddddddbddddddfddddbddddddddfdbdddfddddddbdfdddddddfddddddddddbdddfddddddbddddfddddddddbdddddfdddddbddddddfdddddddbddddfddddddddb
    dfddbddfdddddddbddddddfdddbddddfddddddbddddddfdddbdddddddddfdbdddfdddddddbfddddddddfdddddddddbdddfddddddbdddddfdddddddbdddddfdddddbdddddddfddddddbddddfddddddddd
    fdddbddfddddddbdddddddfdddbddddfddddddbddddddfdddbdddddddddfdbdddfdddddddbfddddddddfdddddddddbdddfddddddbdddddfdddddddbdddddfddddddbddddddfdddddddbddddfdddddddd
    ddddb77777777dbddddddfddddbddddfddddddbddddddfdddbdddddddddfdbdddfdddddddbfddddddddfddddddddddbddfddddddbdddddfdddddddbdddddfddddddbddddddfdddddddbddd777ddddddd
    ddd77df7777d7dbddddddfddddbddddfddddddbddddddfdddbdddddddddfdbdddfdddddddbfddddddddfddddddddddbdddfdddddbdddddfddddddddbdddddfdddddbddddddfdddddddbd777f7777dddd
    dd77ddfd777d7dbddddddfddddbdddfdddddddbddddddfdddbdddddddddfdbdddfdddddddbfddddddddfddddddddddbdddfddddddbddddfddddddddbdddddfdddddbdddddddfddddddb77dd7777d777d
    dd77777777777dbddddddfddddbdddfdddddddbddddddfdddbdddddddddfdbdddfdddddddbfddddddddfddddddddddbdddfddddddbddddfddddddddbdddddfdddddbdddddddfddddd777d77777777d7d
    ddd7dd77777d777ddddddfdddbddddfddddddbdddddddfdddbdddddddddfdbdddfdddddddbfddddddddfddddddddddbdddfddddddbdddddfdddddddbdddddfddddddbddddddfddddd7dbd777777d7777
    dd77777777777777dddddfdddbddddfddddddbddddddfddddbdddddddddfdbdddfdddddddbfddddddddfddddddddddbdddfddddddbdddddfdddddddbdddddfddddddbddddddfddddd7d7777d77777777
    ddb77777d7777bd7ddddfddddbddddfddddddbddddddfddddbdddddddddfdbdddfdddddddbfddddddddfddddddddddbdddfddddddbdddddfddddddddbdddddfdddddbdddddddfdddd7d777777777777d
    dd77777ee777777dddddfddddbddddfddddddbddddddfddddbdddddddddfdbdddfdddddddbfddddddddfdddddddddddbddfddddddbdddddfddddddddbdddddfdddddbdddddddfdddd7d77777777d777d
    d77777777777777dddddfddddbddddfddddddbddddddfddddbdddddddddfdbdddfdddddddbfddddddddfdddddddddddbdddfdddddbdddddfddddddddbdddddfddddddbddddddfdddd7d77777d777777d
    d7ddf7d77e77777dddddfddddbdddfdddddddbddddddfddddbdddddddddfdbdddfdddddddbfddddddddfdddddddddddbdddfddddddbddddfddddddddbdddddfddddddbddddddfddddd777777efd7777d
    db7777de7777777dddddfdddbddddfdddddddbddddddfddddbdddddddddfdbdddfdddddddbfddddddddfdddddddddddbdddfddddddbdddddfdddddddbdddddfddddddbdddddddfddddd77d7eeef777dd
    dbdd77777e77bddddddfddddbddddfdddddddbddddddfddddbdddddddddfdbdddfdddddddbfddddddddfdddddddddddbdddfddddddbdddddfdddddddbddddddfdddddbdddddddfdddddd777ee7777ddd
    dbdd7777777dbddddddfddddbddddfdddddddbddddddfddddbdddddddddfdbdddfdddddddbfddddddddfdddddddddddbdddfddddddbdddddfddddddddbdddddfdddddbdddddddfdddddddbdeeefddddd
    bddfdddeeeebdddddddfddddbddddfddddddbdddddddfddddbdddddddddfdbdddfdddddddbfddddddddfdddddddddddbdddfddddddbdddddfddddddddbdddddfddddddbddddddfdddddddbdeeefddddd
    dddfdddeedebdddddddfddddbddddfddddddbdddddddfddddbdddddddddfdbdddfdddddddbfddddddddfdddddddddddbdddfddddddbdddddfddddddddbdddddfddddddbdddddddfdddddddbeeedfdddd
    dddfddeeeeebdddddddfddddbdddfdddddddbdddddddfddddbdddddddddfdbdddfdddddddbfddddddddfddddddddddddbdddfddddddbddddfddddddddbddddddfdddddbdddddddfdddddddbeeedfdddd
    dddfddeeeeeedddddddfdddbddddfdddddddbdddddddfddddbdddddddddfdbdddfdddddddbfddddddddfddddddddddddbdddfddddddbdddddfdddddddbddddddfdddddbdddddddfdddddddbeeedfdddd
    ddfdddeedebeddddddfddddbddddfdddddddbdddddddfddddbdddddddddfdbdddfdddddddbfddddddddfddddddddddddbdddfddddddbdddddfddddddddbdddddfddddddbddddddfdddddddbeeedfdddd
    ddfdddeeeebeddddddfddddbddddfdddddddbdddddddfddddbdddddddddfdbdddfdddddddbfddddddddfddddddddddddbdddfddddddbdddddfddddddddbdddddffdddddbdddddddfdddddddeeeedfddd
    ddfddeeeeeeeedddddfddddbddddfdddddddbdddddddfddddbdddddddddfdbdddfdddddddbfddddddddfddddddddddddbdddfddddddbdddddfddddddddbdddddffdddddbdddddddfdddddddededdfddd
    ddfddedeeeededddddfddddbddddfdddddddbdddddddfddddbdddddddddfdbdddfdddddddbfddddddddfddddddddddddbdddfddddddbdddddfddddddddbddddddfdddddbdddddddfdddddddbddddfddd
    dfdddeeeeeedeeddddfddddbddddfdddddddbdddddddfddddbdddddddddfdbdddfdddddddbfddddddddfddddddddddddbdddfddddddbdddddfddddddddbddddddfdddddbdddddddfdddddddbddddfddd
    dddddeeddbeddddddfddddbddddfdddddddbdddddddfddddbdddddddddddfdbddfddddddddbfddddddddfddddddddddddbdddfddddddbdddddfddddddddbdddddfddddddbdddddddfdddddddbddddfdd
    `)
game.setGameOverScoringType(game.ScoringType.HighScore)
game.onUpdateInterval(10000, function () {
    bat = sprites.create(img`
        . f f f . . . . . . . . f f f . 
        f f c . . . . . . . f c b b c . 
        f c c . . . . . . f c b b c . . 
        c f . . . . . . . f b c c c . . 
        c f f . . . . . f f b b c c . . 
        f f f c c . c c f b c b b c . . 
        f f f c c c c c f b c c b c . . 
        . f c 3 c c 3 b c b c c c . . . 
        . c b 3 b c 3 b b c c c c . . . 
        c c b b b b b b b b c c . . . . 
        c b 1 b b b 1 b b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        f b c b b b c b b b b f . . . . 
        . f 1 f f f 1 b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `, SpriteKind.Enemy)
    animation.runImageAnimation(
    bat,
    [img`
        . . f f f . . . . . . . . f f f 
        . f f c c . . . . . . f c b b c 
        f f c c . . . . . . f c b b c . 
        f c f c . . . . . . f b c c c . 
        f f f c c . c c . f c b b c c . 
        f f c 3 c c 3 c c f b c b b c . 
        f f b 3 b c 3 b c f b c c b c . 
        . c b b b b b b c b b c c c . . 
        . c 1 b b b 1 b b c c c c . . . 
        c b b b b b b b b b c c . . . . 
        c b c b b b c b b b b f . . . . 
        f b 1 f f f 1 b b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        . f b b b b b b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `,img`
        . . f f f . . . . . . . . . . . 
        f f f c c . . . . . . . . f f f 
        f f c c . . c c . . . f c b b c 
        f f c 3 c c 3 c c f f b b b c . 
        f f b 3 b c 3 b c f b b c c c . 
        . c b b b b b b c f b c b c c . 
        . c b b b b b b c b b c b b c . 
        c b 1 b b b 1 b b b c c c b c . 
        c b b b b b b b b c c c c c . . 
        f b c b b b c b b b b f c . . . 
        f b 1 f f f 1 b b b b f c c . . 
        . f b b b b b b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . c c . . c c . . . . . . . . 
        . . c 3 c c 3 c c c . . . . . . 
        . c b 3 b c 3 b c c c . . . . . 
        . c b b b b b b b b f f . . . . 
        c c b b b b b b b b f f . . . . 
        c b 1 b b b 1 b b c f f f . . . 
        c b b b b b b b b f f f f . . . 
        f b c b b b c b c c b b b . . . 
        f b 1 f f f 1 b f c c c c . . . 
        . f b b b b b b f b b c c . . . 
        c c f b b b b b c c b b c . . . 
        c c c f f f f f f c c b b c . . 
        . c c c . . . . . . c c c c c . 
        . . c c c . . . . . . . c c c c 
        . . . . . . . . . . . . . . . . 
        `,img`
        . f f f . . . . . . . . f f f . 
        f f c . . . . . . . f c b b c . 
        f c c . . . . . . f c b b c . . 
        c f . . . . . . . f b c c c . . 
        c f f . . . . . f f b b c c . . 
        f f f c c . c c f b c b b c . . 
        f f f c c c c c f b c c b c . . 
        . f c 3 c c 3 b c b c c c . . . 
        . c b 3 b c 3 b b c c c c . . . 
        c c b b b b b b b b c c . . . . 
        c b 1 b b b 1 b b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        f b c b b b c b b b b f . . . . 
        . f 1 f f f 1 b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `],
    500,
    true
    )
    random_loc_1 = randint(0, 160)
    random_loc_2 = randint(0, 160)
    random_loc_3 = randint(0, 160)
    random_loc_4 = randint(0, 160)
    bat.setPosition(random_loc_1, random_loc_4)
    bat.follow(mySprite, 20)
    snake = sprites.create(img`
        . . . . . c c c c c c c . . . . 
        . . . . c 6 7 7 7 7 7 6 c . . . 
        . . . c 7 c 6 6 6 6 c 7 6 c . . 
        . . c 6 7 6 f 6 6 f 6 7 7 c . . 
        . . c 7 7 7 7 7 7 7 7 7 7 c . . 
        . . f 7 8 1 f f 1 6 7 7 7 f . . 
        . . f 6 f 1 f f 1 f 7 7 7 f . . 
        . . . f f 2 2 2 2 f 7 7 6 f . . 
        . . c c f 2 2 2 2 7 7 6 f c . . 
        . c 7 7 7 7 7 7 7 7 c c 7 7 c . 
        c 7 1 1 1 7 7 7 7 f c 6 7 7 7 c 
        f 1 1 1 1 1 7 6 f c c 6 6 6 c c 
        f 1 1 1 1 1 1 6 6 c 6 6 6 c . . 
        f 6 1 1 1 1 1 6 6 6 6 6 6 c . . 
        . f 6 1 1 1 1 1 6 6 6 6 c . . . 
        . . f f c c c c c c c c . . . . 
        `, SpriteKind.Enemy)
    animation.runImageAnimation(
    snake,
    [img`
        . . . . c c c c c c . . . . . . 
        . . . c 6 7 7 7 7 6 c . . . . . 
        . . c 7 7 7 7 7 7 7 7 c . . . . 
        . c 6 7 7 7 7 7 7 7 7 6 c . . . 
        . c 7 c 6 6 6 6 c 7 7 7 c . . . 
        . f 7 6 f 6 6 f 6 7 7 7 f . . . 
        . f 7 7 7 7 7 7 7 7 7 7 f . . . 
        . . f 7 7 7 7 6 c 7 7 6 f c . . 
        . . . f c c c c 7 7 6 f 7 7 c . 
        . . c 7 2 7 7 7 6 c f 7 7 7 7 c 
        . c 7 7 2 7 7 c f c 6 7 7 6 c c 
        c 1 1 1 1 7 6 f c c 6 6 6 c . . 
        f 1 1 1 1 1 6 6 c 6 6 6 6 f . . 
        f 6 1 1 1 1 1 6 6 6 6 6 c f . . 
        . f 6 1 1 1 1 1 1 6 6 6 f . . . 
        . . c c c c c c c c c f . . . . 
        `,img`
        . . . c c c c c c . . . . . . . 
        . . c 6 7 7 7 7 6 c . . . . . . 
        . c 7 7 7 7 7 7 7 7 c . . . . . 
        c 6 7 7 7 7 7 7 7 7 6 c . . . . 
        c 7 c 6 6 6 6 c 7 7 7 c . . . . 
        f 7 6 f 6 6 f 6 7 7 7 f . . . . 
        f 7 7 7 7 7 7 7 7 7 7 f . . . . 
        . f 7 7 7 7 6 c 7 7 6 f . . . . 
        . . f c c c c 7 7 6 f c c c . . 
        . . c 6 2 7 7 7 f c c 7 7 7 c . 
        . c 6 7 7 2 7 7 c f 6 7 7 7 7 c 
        . c 1 1 1 1 7 6 6 c 6 6 6 c c c 
        . c 1 1 1 1 1 6 6 6 6 6 6 c . . 
        . c 6 1 1 1 1 1 6 6 6 6 6 c . . 
        . . c 6 1 1 1 1 1 7 6 6 c c . . 
        . . . c c c c c c c c c c . . . 
        `],
    500,
    true
    )
    random_loc_2 = randint(0, 160)
    snake.setPosition(random_loc_2, random_loc_1)
    snake.follow(mySprite, 5)
    skeleton = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    animation.runImageAnimation(
    skeleton,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111ffff.....
        ......fffcdb1bc111cf....
        ....fc111cbfbf1b1b1f....
        ....f1b1b1ffffbfbfbf....
        ....fbfbfffffff.........
        .........fffff..........
        ..........fff...........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .....ffff111111bf.......
        ....fc111cdb1bdfff......
        ....f1b1bcbfbfc111cf....
        ....fbfbfbffff1b1b1f....
        .........fffffffbfbf....
        ..........fffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `],
    500,
    true
    )
    random_loc_3 = randint(0, 160)
    skeleton.setPosition(random_loc_3, random_loc_4)
    skeleton.follow(mySprite, 10)
    dragon = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . c c c c . . . . . . . . 
        . . c c 5 5 5 5 c c . . . . . . 
        . c 5 5 5 5 5 5 5 5 c . . . . . 
        c 5 5 5 5 5 1 f 5 5 5 c . . . . 
        c 5 5 5 5 5 f f 5 5 5 5 c . . . 
        c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
        c c b b 1 b 5 5 5 5 5 5 d c . . 
        c 5 3 3 3 5 5 5 5 5 d d d c . . 
        . b 5 5 5 5 5 5 5 5 d d d c . . 
        . . c b b c 5 5 b d d d d c c . 
        . c b b c 5 5 b b d d d d c d c 
        . c c c c c c d d d d d d d d c 
        . . . c c c c d 5 5 b d d d c . 
        . . c c c c c b 5 5 b c c c . . 
        . . c b b b c d 5 5 b c . . . . 
        `, SpriteKind.Enemy)
    random_loc_4 = randint(0, 160)
    dragon.setPosition(random_loc_4, random_loc_2)
    animation.runImageAnimation(
    dragon,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . c c c c . . . . . . . . 
        . . c c 5 5 5 5 c c . . . . . . 
        . c 5 5 5 5 5 5 5 5 c . . . . . 
        c 5 5 5 5 5 1 f 5 5 5 c . . . . 
        c 5 5 5 5 5 f f 5 5 5 5 c . . . 
        c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
        c c b b 1 b 5 5 5 5 5 5 d c . . 
        c 5 3 3 3 5 5 5 5 5 d d d c . . 
        . b 5 5 5 5 5 5 5 5 d d d c . . 
        . . c b b c 5 5 b d d d d c c . 
        . c b b c 5 5 b b d d d d c d c 
        . c c c c c c d d d d d d d d c 
        . . . c c c c d 5 5 b d d d c . 
        . . c c c c c b 5 5 b c c c . . 
        . . c b b b c d 5 5 b c . . . . 
        `,img`
        . . . . c c c c c . . . . . . . 
        . . c c 5 5 5 5 5 c . . . . . . 
        . c 5 5 5 5 1 f 5 5 c . . . . . 
        c 5 5 5 5 5 f f 5 5 5 c . . . . 
        c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
        c c b b 1 b 5 5 5 5 5 5 c . . . 
        c 5 3 3 3 5 5 5 5 5 5 5 d c . . 
        c 5 3 3 3 5 5 5 5 5 d d d c . . 
        . c 5 5 5 5 b 5 5 5 d d d c . . 
        . . c b b c 5 5 b d d d d c . . 
        . c b b c 5 5 b b d d d d c c c 
        . c c c c c c d d d d d d d d c 
        . . . . c c c b 5 5 b d d d c . 
        . . . . . c d 5 5 b b c c c . . 
        . . . . c c c c c c c . . . . . 
        . . . . c b b b c . . . . . . . 
        `,img`
        . . . . c c c c c . . . . . . . 
        . . c c 5 5 5 5 5 c . . . . . . 
        . c 5 5 5 5 1 f 5 5 c . . . . . 
        c 5 5 5 5 5 f f 5 5 5 c . . . . 
        c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
        c c b b 1 b 5 5 5 5 5 5 c . . . 
        c 5 3 3 3 5 5 5 5 5 5 5 d c . . 
        c 5 5 5 5 5 5 5 5 5 d d d c . . 
        . c 5 5 5 5 b 5 5 5 d d d c . . 
        . . c b b c 5 5 b d d d d c . . 
        . c b b c 5 5 b b d d d d c c c 
        . c c c c c c d d d d d d d d c 
        . . . . c c b 5 5 b d d d c c . 
        . . . . c d 5 5 b b c c c . . . 
        . . . . c c c c c c c . . . . . 
        . . . . c b b b c . . . . . . . 
        `,img`
        . . . . c c c c c . . . . . . . 
        . . c c 5 5 5 5 5 c . . . . . . 
        . c 5 5 5 5 1 f 5 5 c . . . . . 
        c 5 5 5 5 5 f f 5 5 5 c . . . . 
        c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
        c c b b 1 b 5 5 5 5 5 5 c . . . 
        c 5 3 3 3 5 5 5 5 5 5 5 d c . . 
        c 5 5 5 5 5 5 5 5 5 d d d c . . 
        . c 5 5 5 5 b 5 5 5 d d d c . . 
        . . c b b c 5 5 b d d d d c . . 
        . c b b c 5 5 b b d d d d c c . 
        . c c c c c b b d d d d d d c c 
        . . . c c 5 5 b 5 5 d d d d d c 
        . . . . c b 5 5 b b c c c c c c 
        . . . . c c c c c c . . . . . . 
        . . . . . c b b b c . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . c c c c . . . . . . . . 
        . . c c 5 5 5 5 c c . . . . . . 
        . c 5 5 5 5 5 5 5 5 c . . . . . 
        c 5 5 5 5 5 1 f 5 5 5 c . . . . 
        c 5 5 5 5 5 f f 5 5 5 5 c . . . 
        c c b b 1 b 5 5 5 5 5 5 c . . . 
        c c 3 3 b b 5 5 5 5 5 5 d c . . 
        c 5 3 3 3 5 5 5 5 5 d d d c . . 
        . b 5 5 5 5 5 5 5 5 d d d c . . 
        . . c b b c 5 5 b d d d d c . . 
        . c b b c 5 5 b b d d d d c c c 
        . c c c c c c d d d d d d d d c 
        . . . c c c c d 5 5 b d d d c c 
        . . . c b c c b 5 5 b c c c . . 
        . . . c c c d 5 5 b c . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . c c c c . . . . . . . . 
        . . c c 5 5 5 5 c c . . . . . . 
        . c 5 5 5 5 5 5 5 5 c . . . . . 
        c 5 5 5 5 5 1 f 5 5 5 c . . . . 
        c 5 5 5 5 5 f f 5 5 5 5 c . . . 
        c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
        c c b b 1 b 5 5 5 5 5 5 d c . . 
        c 5 3 3 3 5 5 5 5 5 d d d c . . 
        . b 5 5 5 5 5 5 5 5 d d d c . . 
        . . c b b c 5 5 b d d d d c . . 
        . c b b c 5 5 b b d d d d c c c 
        . c c c c c c d d d d d d d d c 
        . . . c c c c d 5 5 b d d c c . 
        . . c b b c c c 5 5 b c c . . . 
        . . c c c c c d 5 5 c . . . . . 
        `],
    500,
    true
    )
    dragon.follow(mySprite, 5)
})
